export { default as FAQs } from './faqs/FAQs'
export { default as Features } from './features/Features'
export { default as Footer } from './footer/Footer'
export { default as Hero } from './hero/Hero'
export { default as WhatGAT } from './whatGAT/WhatGAT'
export { default as Products } from './products/Products'
export { default as Services } from './services/Services'
